version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: resume-app-postgres
    environment:
      POSTGRES_DB: resumeapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - resume-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: resume-app-server
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/resumeapp
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"
    networks:
      - resume-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: resume-app-client
    depends_on:
      - server
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8080/api
    networks:
      - resume-network

networks:
  resume-network:
    driver: bridge

volumes:
  postgres-data: